CREATE DATABASE HR_ANALYTICS ;
USE HR_ANALYTICS;
SELECT * FROM HRDATA;
-- TOTAL NO OF EMPLOYEES 
SELECT COUNT(EMPID) FROM HRDATA;
-- TOTAL ATTRITION VALUE
SELECT COUNT(ATTRITION) FROM HRDATA WHERE Attrition = 1;
-- PERCENTAGE OF ATTRITION VALUE 
SELECT COUNT(CASE WHEN ATTRITION = 1 THEN 1 END) * 100.0 /COUNT(EMPID) FROM HRDATA;
-- AVERAGE AGE
SELECT AVG(AGE) FROM HRDATA;
-- AVERAGAE SALARY 
SELECT AVG(MONTHLYINCOME)/1000.0 FROM HRDATA;
-- AVERAGE YEARS AT COMPANY 
SELECT AVG(YEARSATCOMPANY) FROM HRDATA;
-- ATTRITION BY GENDER 
SELECT GENDER, COUNT(GENDER) 
FROM HRDATA
WHERE Attrition = 1
GROUP BY GENDER;
-- ATTRITION BY EDUCATION 
SELECT EDUCATIONFIELD ,COUNT(CASE WHEN Attrition = 1 THEN 1 END) * 100/COUNT(*) AS ATTRITION_PERCENTAGE 
FROM HRDATA
GROUP BY EducationField;
-- ATTRITION BY AGE
SELECT AGEGROUP , COUNT(CASE WHEN ATTRITION = 1 THEN 1 END)
FROM HRDATA
GROUP BY AGEGROUP;
-- ATTRITION BY SALARY 
SELECT SalarySlab  , COUNT(CASE WHEN ATTRITION = 1 THEN 1 END)
FROM HRDATA 
GROUP BY SalarySlab;
-- ATTRITION BY JOB ROLE
SELECT JOBROLE , COUNT(CASE WHEN ATTRITION = 1 THEN 1 END)
FROM HRDATA 
GROUP BY JOBROLE;
-- SUM OF EMPLOYEES AT DIFFERENT JOB ROLES
SELECT JOBROLE,COUNT(*)
FROM HRDATA
GROUP BY JOBROLE;
-- STORED PRICEDURE TO VIEW DETAILS OF EDUCATION TYPE 3 
CREATE PROCEDURE PROC_NEW
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM HRDATA WHERE Education = 3;
END;
GO
EXECUTE PROC_NEW;
DROP PROC PROC_NEW;
-- CREATED VIEW TO VIEW ATTRITION BY AGE 
CREATE VIEW vw_AgewiseAttrition AS
SELECT 
    AgeGroup, 
    COUNT(CASE WHEN Attrition = 1 THEN 1 END) AS Attrition_Count
FROM HRData
GROUP BY AgeGroup;
SELECT * FROM vw_AgewiseAttrition;